CREATE TABLE uczen (ID_UCZEN INT (10) AUTO_INCREMENT, IMIE VARCHAR(20), NAZWISKO VARCHAR(20), MIASTO VARCHAR(20), ULICA VARCHAR(20), NR_DOMU VARCHAR(20), PRIMARY KEY (ID_UCZEN));
CREATE TABLE miasto (ID_MIASTO INT (10) AUTO_INCREMENT, NAZWA_MIASTA VARCHAR(20), PRIMARY KEY (ID_MIASTO));
CREATE TABLE nauczyciele (ID_NAUCZ INT (10) AUTO_INCREMENT, IMIE VARCHAR(30), NAZWISKO VARCHAR(30), TELEFON VARCHAR(30),  PRIMARY KEY (ID_NAUCZ));
CREATE TABLE przedmiot (ID_PRZE INT (10) AUTO_INCREMENT, NAZWA_PRZEDMIOTU VARCHAR(20), PRIMARY KEY (ID_PRZE));
CREATE TABLE dzienniczek (ID_DZIENNICZEK INT (10) AUTO_INCREMENT, ID_UCZEN INT (10),ID_NAUCZ INT (10),ID_OCENA INT (10),ID_PRZE INT (10),DATA_WYST DATE, PRIMARY KEY (ID_DZIENNICZEK));
CREATE TABLE ocena (ID_OCENA INT (10) AUTO_INCREMENT, NAZWA_OCENY VARCHAR(20), PRIMARY KEY (ID_OCENA));
CREATE TABLE KLASA (ID_KLASA INT (10) AUTO_INCREMENT, NAZWA_KLASY VARCHAR(20), PRIMARY KEY (ID_KLASA));
CREATE TABLE U_W_K (ID_U_W_K INT(10) AUTO_INCREMENT, ID_UCZEN INT(10), ID_KLASA INT(10), PRIMARY KEY (ID_U_W_K));
