INSERT INTO LICZBY(LICZBA_A,LICZBA_B) VALUES (3,3);
INSERT INTO LICZBY(LICZBA_A,LICZBA_B) VALUES (1,2);
INSERT INTO LICZBY(LICZBA_A,LICZBA_B) VALUES (2,5);
INSERT INTO LICZBY(LICZBA_A,LICZBA_B) VALUES (4,8);
INSERT INTO LICZBY(LICZBA_A,LICZBA_B) VALUES (9,7);